# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 06:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='zip_code',
            new_name='z_code',
        ),
    ]
