# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='itemid',
            field=models.CharField(max_length=40),
        ),
    ]
