# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20161025_0658'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='top_favorites',
            field=models.ManyToManyField(related_name='top_favs', to='login.User'),
        ),
    ]
