# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20161027_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='units',
            field=models.CharField(default='Nothing', max_length=20),
        ),
    ]
