# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20161026_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='isprivate',
            field=models.BooleanField(default=False),
        ),
    ]
