# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipes_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='units',
            field=models.CharField(default="{ 'qty': 'Nothing', 'unit':'Nothing'", max_length=20),
        ),
    ]
