# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipes_isprivate'),
        ('recipes', '0002_auto_20161026_2226'),
    ]

    operations = [
    ]
