# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 00:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipes_top_favorites'),
        ('recipes', '0004_auto_20161027_2251'),
    ]

    operations = [
    ]
