# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_merge_20161028_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='units',
            field=models.CharField(default="{ 'ing': 'Nothing?', 'qty': 'Nothing', 'unit':'Nothing' }", max_length=20),
        ),
    ]
