# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20161028_0056'),
        ('recipes', '0005_merge_20161028_0030'),
    ]

    operations = [
    ]
