# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_merge_20161028_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='itemid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='units',
            field=models.TextField(default="{ 'ing': 'Nothing?', 'qty': 'Nothing', 'unit':'Nothing' }"),
        ),
    ]
