# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 18:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20161028_1952'),
        ('recipes', '0007_merge_20161028_0239'),
    ]

    operations = [
    ]
